using System.Collections.Generic;
using System.Linq;

namespace eva.core.framework.framework
{
    /// <summary>
    /// An abstract class depecting Worker Agents
    /// </summary>
    public abstract class WorkerAgent : Agent
    {
        /// <summary>
        /// Every agent has to have an activator and a selector
        /// </summary>
        /// <param name="act">the activator checks if the agent has to be activated</param>
        /// <param name="sct">the selector selects solutions on which the agent runs</param>
        public WorkerAgent(IAgentActivator act, ISelector sct) : base(act, sct)
        {
        }
        /// <summary>
        /// works on the selected solution to produce a new solution
        /// </summary>
        /// <param name="selected">the selected solutions</param>
        /// <param name="sm">the solution manager to work with</param>
        /// <returns>list of newly created solutions</returns>
        abstract protected IEnumerable<ISolution> runWithSolutions(IEnumerable<ISolution> selected,ISolutionManger sm);

        /// <summary>
        /// First checks if the solution is activated and then creates new solution
        /// then inserts the newly created solutions into the database after assinging
        /// them a batch id and solution id else returns an empty solution
        /// </summary>
        /// <param name="sm">the solution manager to be used while running the agent</param>
        /// <returns>the solutions generated by the agent</returns>
        public override IEnumerable<ISolution> run(ISolutionManger sm)
        {
            var temp=new List<ISolution>();
            // check if agent is active
            if (activate(sm))
            {
                //create modified solutions and insert them into the database after 
                //attaching a solution and bacth id
                return insertIntoDatabase(runWithSolutions(select(sm),sm).Select(x =>
                {
                    x.solutionid = generateId.getId();
                    x.batchid = batchid;
                    return x;
                }));
            }
            return temp;
        }

    }
}
